### PR TITLE
Handle ES6 Map and Set

### PR DESCRIPTION
**Pull request by zalmoxisus**
@kolodny please review. If it's ok, I'll add also support for `Set` in the same way.

### CODE REVIEW

**Comment by kolodny** [comment]
Awesome! Can you merge and publish a new release? Thanks!

**Comment by zalmoxisus** [comment]
@kolodny, sure.

The small issue here is that if we have:
```js
var obj = { /*...*/};
var data =  { obj: obj, obj2: obj, map: new Map([[obj, {obj: obj, obj2: obj}]]) };
jsan.stringify(data, null, null, true);
```

we'll get:
`{"obj":{},"obj2":{"$jsan":"$.obj"},"map":{"$jsan":"m[[{},{\"obj\":{\"$jsan\":\"$[0][0]\"},\"obj2\":{\"$jsan\":\"$[0][0]\"}}]]"}}`

Not sure if losing the reference inside the map (as it is stringified and parsed separately) would be an issue for some use cases. I don't see a easy implementation to support that.

**Comment by zalmoxisus** [comment]
Added also support for `Set`. Since `s` is reserved for symbols, I used `l` (as I see them like lists), but we could also use `S` in the upper case. Hope we'll not run out of letters one day 😂

Please give it another look when you have time.

**Comment by kolodny** [comment]
LGTM, ship it. Don't worry we're not limited to ascii 😉

**Pull request merged**
